export const SITE = {
  name: "Chimney Peak California",
  shortName: "Chimney Peak CA",
  // Set phone + phoneHref here when a real tracking number is ready — all components read from this one place.
  phone: "",
  phoneHref: "",
  email: "info@chimneycleaningca.com",
  address: "Los Angeles, CA",
  baseUrl: "https://www.californiachimneyservices.com",
  googleRating: "4.9",
  reviewCount: "847",
  yearsInBusiness: "15",
  jobsCompleted: "12,400",
  trustCopy: "Professional Chimney Service Team",
};

export const NAV_SERVICES = [
  { name: "Chimney Cleaning", href: "/services/chimney-cleaning/" },
  { name: "Chimney Sweep", href: "/services/chimney-sweep/" },
  { name: "Chimney Inspection", href: "/services/chimney-inspection/" },
  { name: "Chimney Repair", href: "/services/chimney-repair/" },
  { name: "Fireplace Cleaning", href: "/services/fireplace-cleaning/" },
  { name: "Chimney Cap Installation", href: "/services/chimney-cap-installation/" },
  { name: "Chimney Liner Repair", href: "/services/chimney-liner-repair/" },
  { name: "Dryer Vent Cleaning", href: "/services/dryer-vent-cleaning/" },
  { name: "Fireplace Installation", href: "/services/fireplace-installation/" },
];

export const NAV_AREAS = [
  { name: "Los Angeles", href: "/areas/los-angeles/" },
  { name: "San Diego", href: "/areas/san-diego/" },
  { name: "San Jose", href: "/areas/san-jose/" },
  { name: "San Francisco", href: "/areas/san-francisco/" },
  { name: "Sacramento", href: "/areas/sacramento/" },
  { name: "Fresno", href: "/areas/fresno/" },
  { name: "Oakland", href: "/areas/oakland/" },
  { name: "Long Beach", href: "/areas/long-beach/" },
  { name: "Anaheim", href: "/areas/anaheim/" },
  // — footer shows slice(0,9) above; items below appear in site nav and California page —
  { name: "Irvine", href: "/areas/irvine/" },
  { name: "Riverside", href: "/areas/riverside/" },
  { name: "Bakersfield", href: "/areas/bakersfield/" },
  { name: "Stockton", href: "/areas/stockton/" },
  { name: "Modesto", href: "/areas/modesto/" },
  { name: "Santa Rosa", href: "/areas/santa-rosa/" },
  { name: "Pasadena", href: "/areas/pasadena/" },
  { name: "Glendale", href: "/areas/glendale/" },
  { name: "Santa Barbara", href: "/areas/santa-barbara/" },
  { name: "Santa Monica", href: "/areas/santa-monica/" },
  { name: "Santa Clarita", href: "/areas/santa-clarita/" },
  { name: "Oxnard", href: "/areas/oxnard/" },
  { name: "Moreno Valley", href: "/areas/moreno-valley/" },
  { name: "Huntington Beach", href: "/areas/huntington-beach/" },
  { name: "Elk Grove", href: "/areas/elk-grove/" },
  { name: "Ontario", href: "/areas/ontario/" },
  { name: "Rancho Cucamonga", href: "/areas/rancho-cucamonga/" },
  { name: "Oceanside", href: "/areas/oceanside/" },
  { name: "Lancaster", href: "/areas/lancaster/" },
  { name: "Roseville", href: "/areas/roseville/" },
  { name: "Concord", href: "/areas/concord/" },
  { name: "Thousand Oaks", href: "/areas/thousand-oaks/" },
  { name: "Sunnyvale", href: "/areas/sunnyvale/" },
  { name: "Corona", href: "/areas/corona/" },
  { name: "Salinas", href: "/areas/salinas/" },
  { name: "Torrance", href: "/areas/torrance/" },
  { name: "Fremont", href: "/areas/fremont/" },
  { name: "Hayward", href: "/areas/hayward/" },
  { name: "Pomona", href: "/areas/pomona/" },
  { name: "Escondido", href: "/areas/escondido/" },
];
